package com.apiux.docux.proceduremanager;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class procedureManagerDTO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "\u00BFReasigna?")
   private java.lang.Boolean isReasign;

   public procedureManagerDTO()
   {
   }

   public java.lang.Boolean getIsReasign()
   {
      return this.isReasign;
   }

   public void setIsReasign(java.lang.Boolean isReasign)
   {
      this.isReasign = isReasign;
   }

   public procedureManagerDTO(java.lang.Boolean isReasign)
   {
      this.isReasign = isReasign;
   }

}