package com.apiux.docux.proceduremanager;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class procedureManagerDTO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public procedureManagerDTO() {
    }

}